# Generated by Django 5.0 on 2023-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenmessage',
            name='type',
            field=models.CharField(choices=[('seen', 'seen'), ('owndelete', 'owndelete')], max_length=15),
        ),
    ]
