# Generated by Django 5.0 on 2023-12-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_reply_delete_replymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='parent'),
        ),
    ]
